[package]
name = "mandelbrot-wasm"
version = "0.1.0"
edition = "2021"

[build]
target = "wasm64-unknown-unknown"

[lib]
crate-type = ["cdylib"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
wasm-bindgen = "0.2.73"
num = "0.4.0"
